// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrAypF_8AtuUkDBVyIER31VElHpFZENys',
    appId: '1:564580384660:web:a3fe02ee7690a7799bd981',
    messagingSenderId: '564580384660',
    projectId: 'eduassess-52e66',
    authDomain: 'eduassess-52e66.firebaseapp.com',
    storageBucket: 'eduassess-52e66.appspot.com',
    measurementId: 'G-52LLH59N0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdGqRS5jxn0j1aLPdSwl3UDRkMKw6N_GE',
    appId: '1:564580384660:android:9772723531c7022b9bd981',
    messagingSenderId: '564580384660',
    projectId: 'eduassess-52e66',
    storageBucket: 'eduassess-52e66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsQyTOHRu5bovPhBmsphcMcHp-HRHqMAQ',
    appId: '1:564580384660:ios:d3b366986da57a429bd981',
    messagingSenderId: '564580384660',
    projectId: 'eduassess-52e66',
    storageBucket: 'eduassess-52e66.appspot.com',
    iosBundleId: 'com.example.testAgain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsQyTOHRu5bovPhBmsphcMcHp-HRHqMAQ',
    appId: '1:564580384660:ios:d3b366986da57a429bd981',
    messagingSenderId: '564580384660',
    projectId: 'eduassess-52e66',
    storageBucket: 'eduassess-52e66.appspot.com',
    iosBundleId: 'com.example.testAgain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrAypF_8AtuUkDBVyIER31VElHpFZENys',
    appId: '1:564580384660:web:801b6ee85c44e5f09bd981',
    messagingSenderId: '564580384660',
    projectId: 'eduassess-52e66',
    authDomain: 'eduassess-52e66.firebaseapp.com',
    storageBucket: 'eduassess-52e66.appspot.com',
    measurementId: 'G-0616F26B2R',
  );
}
